FROM eclipse-temurin:17

WORKDIR /app

COPY . .

# Compile all Java files (safe for folders too)
RUN find . -name "*.java" > sources.txt && \
    javac -cp ".:lib/mysql-connector-j-9.7.0.jar" @sources.txt

EXPOSE 4567

CMD ["java", "-cp", ".:lib/mysql-connector-j-9.7.0.jar", "VotingApi"]